elk/rspec_GENI.xml

Added rspec file for GENI

---

elk/beats/README.md

Fixing typing error

---

owl/README.md

Setting up new feature for one way latency check.

Adding OWL

---

elk/FABRIC_README.md

Testing merge from a new branch dev-elk-song

testing new branch

---

instrumentize/prometheus/ansible/roles/common/files/alert_rules/network_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/node_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/recording_rules/isis_rules.yml
instrumentize/prometheus/ansible/roles/common/tasks/Prometheus/add_recording_rules.yml
instrumentize/prometheus/ansible/roles/fabric_central/defaults/main.yml
instrumentize/prometheus/ansible/roles/fabric_central/templates/Grafana/grafana_custom.ini.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Grafana/grafana_env.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/fabric_beta_http_targets.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/prometheus_config.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/workernode_ping_targets.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Thanos/stores.yml.j2
instrumentize/prometheus/ansible/roles/fabric_rack/defaults/main.yml
instrumentize/prometheus/ansible/roles/fabric_rack/files/recording_rules
instrumentize/prometheus/ansible/roles/fabric_rack/tasks/fabric_rack_install_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_rack/templates/Prometheus/vpn_ping_targets.yml.j2

Added recording rules, alert updates, thanos exporters and other small fixes .

Prom compose

---

instrumentize/prometheus/ansible/roles/common/files/blackbox_config.yml
instrumentize/prometheus/ansible/roles/common/tasks/setup_tasks/setup_docker_ipv6_network_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_central/defaults/main.yml
instrumentize/prometheus/ansible/roles/fabric_central/tasks/fabric_central_install_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/central_bastion_ping6_targets.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/central_bastion_ping_targets.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/central_other_ping_targets.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Prometheus/prometheus_config.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/Thanos/stores.yml.j2
instrumentize/prometheus/ansible/roles/fabric_rack/tasks/fabric_rack_install_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_rack/templates/Prometheus/local_rack_ping_targets.yml.j2

Added central pings for all rack devices.
Updated local rack pings.
Fixed central grafana dual stack ip addresses.

Central ping dev

---

user_services/elk/service_commands/custom_dashboards.py
user_services/elk/service_commands/update.py

Just adding changes to elk dashboard import.

Adding elk custom dashboard files from Chas

---

instrumentize/prometheus/ansible/roles/common/files/alert_rules/docker_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/network_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/node_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/prometheus_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/time_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/files/alert_rules/vpn_ping_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/tasks/Thanos/thanos_sidecar_container_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_rack/defaults/main.yml
instrumentize/prometheus/ansible/roles/fabric_rack/tasks/fabric_rack_install_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_rack/templates/Prometheus/prometheus_config.yml.j2

Ipv4 & ipv6 racks tested to work with docker.

Dualrack install

---

instrumentize/prometheus/ansible/roles/common/files/alert_rules/node_alert_rules.yml

Increasing temp to reduce uneeded alerts.

Changed HostPhysicalComponentTooHot temperature to 75.

---

instrumentize/prometheus/ansible/roles/common/tasks/Prometheus/prometheus_container_tasks.yml
instrumentize/prometheus/ansible/roles/fabric_rack/defaults/main.yml

Just adding retentions time to promtheus container start.

Adding var to set prom tsdp retention time.

---

instrumentize/prometheus/ansible/roles/common/files/alert_rules/vpn_ping_alert_rules.yml

Removing nearly duplicate rule.

Removed extra VPNPingFailing (note ING not ED) rule with response typo.

---

instrumentize/prometheus/ansible/roles/common/files/alert_rules/time_alert_rules.yml
instrumentize/prometheus/ansible/roles/common/templates/Thanos/object_store_config.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/defaults/main.yml
instrumentize/prometheus/ansible/roles/fabric_central/templates/Thanos/object_store_config.yml.j2

Minio rack update

---

instrumentize/ansible/playbook_fabric_experiment_install_prometheus.yml

Broke mflib instrumentize, so this merge replaces it.

Replacing removed ansible playbook for fabric experiment.

---

instrumentize/ansible/playbook_fabric_experiment_install_prometheus.yml
instrumentize/prometheus/ansible/roles/fabric_central/templates/DockerCompose/docker_compose_prometheus_fragment.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/DockerCompose/docker_compose_thanos_query_fragment.yml.j2
instrumentize/prometheus/ansible/roles/fabric_central/templates/DockerCompose/docker_compose_thanos_store_fragment.yml.j2
instrumentize/prometheus/ansible/roles/fabric_ping_plus/templates/Prometheus/fabric_http_targets.yml.j2

Ver4 fixes

---

user_services/elk/service_commands/info.py
user_services/elk/service_commands/update.py
user_services/overview/service_commands/info.py

Added in functionality for the ELK Data Export Service

Data export service

---

instrumentize/elk/fabric_deploy.yml
user_services/timestamp/timestamp/service_files/timestampservice.py

Underbar fix has been tested to change _meas_node to meas-node

Changed _meas_node to meas-node.

---

instrumentize/experiment_bootstrap/bootstrap.yml
instrumentize/experiment_bootstrap/pip3_docker_sdk_playbook.yml

Emergency fix of urllib3 update that has broken docker-py lib.

Urllib fix

---

instrumentize/elk/docker-images/elk/docker-compose.yml
instrumentize/elk/docker-images/elk/elasticsearch/config/elasticsearch.yml
instrumentize/prometheus/ansible/roles/common/tasks/Prometheus/prometheus_container_tasks.yml

Allows creating snapshots and shared volumes

Small config changes to allow for creating snapchats 

---

user_services/owl/owl/sock_ops/send_data.py

2 commits; one for the addition of new function (push to Cloud), and one for correction of comment strings.

Allow parse and send to InfluxDB Cloud

---

user_services/owl/owl/sock_ops/send_data.py

This will catch errors like having an empty `packet_data` (which can result from I/O errors from `tcpdump`).
If there were errors in the creation of the data to be written, the program will not write anything to the destination InfluxDB server. The error that led to this fix is below. Due to probable I/O error in the packet dump generation, `packet_data` remained an empty dictionary, leading to a KeyError:
```
Traceback (most recent call last):
File "/MeasurementFramework/user_services/owl/owl/sock_ops/send_data.py", line 150, in <module>
parse_and_send(pcap_file, verbose=verbose, influxdb_token=token, influxdb_org=org, 
File "/MeasurementFramework/user_services/owl/owl/sock_ops/send_data.py", line 113, in parse_and_send
.field("latency", int(packet_data["latency"]))
KeyError: 'latency' …
```

Add try/except block around the data-write calls.
